# Generated by Django 5.0.3 on 2024-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Number_of_Volunteer', models.PositiveIntegerField(verbose_name='Number of Volunteers')),
                ('Size_of_Event', models.PositiveIntegerField(verbose_name='Size of Event')),
                ('Event_Name', models.CharField(max_length=20, verbose_name='Event Name')),
                ('Event_Description', models.TextField(default='Test dicription', verbose_name='Event Discription')),
                ('Location', models.CharField(max_length=20, verbose_name='Location')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Registration_option', models.BooleanField(default=True)),
                ('Event_Date', models.DateTimeField(null=True)),
                ('Event_Status', models.CharField(choices=[('PAST', 'Past'), ('COMING', 'Coming')], default='COMING', max_length=20)),
            ],
        ),
    ]
