# Generated by Django 5.0.3 on 2024-03-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Created_Org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducting_Org', to='Org.org'),
        ),
    ]
