# Generated by Django 5.0.3 on 2024-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_events_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Event_Description',
            field=models.TextField(default='', verbose_name='Event Discription'),
        ),
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
