# Generated by Django 5.0.3 on 2024-03-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_alter_events_event_description_alter_events_poster'),
        ('Volunteer', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Events.events')),
                ('Volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_vols', to='Volunteer.volunteer')),
            ],
        ),
    ]
