# Generated by Django 5.0.3 on 2024-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_registered_volunteers_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
