# Generated by Django 5.0.3 on 2024-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('Org_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Org_Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
