# Generated by Django 5.0.3 on 2024-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Org', '0003_alter_org_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='profile',
            field=models.ImageField(default='', upload_to='org_profile/'),
        ),
    ]
