# Generated by Django 5.0.3 on 2024-03-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('Vol_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='vol_profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vol_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
