# Generated by Django 5.0.3 on 2024-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Vol_ID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
